// Code generated by go-swagger; DO NOT EDIT.

package account_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tooolbox/firstvision/models"
)

// TriadDecisionInquiryV1FvEmeaReader is a Reader for the TriadDecisionInquiryV1FvEmea structure.
type TriadDecisionInquiryV1FvEmeaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TriadDecisionInquiryV1FvEmeaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTriadDecisionInquiryV1FvEmeaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTriadDecisionInquiryV1FvEmeaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewTriadDecisionInquiryV1FvEmeaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewTriadDecisionInquiryV1FvEmeaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewTriadDecisionInquiryV1FvEmeaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewTriadDecisionInquiryV1FvEmeaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 452:
		result := NewTriadDecisionInquiryV1FvEmeaStatus452()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 453:
		result := NewTriadDecisionInquiryV1FvEmeaStatus453()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 455:
		result := NewTriadDecisionInquiryV1FvEmeaStatus455()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTriadDecisionInquiryV1FvEmeaOK creates a TriadDecisionInquiryV1FvEmeaOK with default headers values
func NewTriadDecisionInquiryV1FvEmeaOK() *TriadDecisionInquiryV1FvEmeaOK {
	return &TriadDecisionInquiryV1FvEmeaOK{}
}

/*TriadDecisionInquiryV1FvEmeaOK handles this case with default header values.

successful operation
*/
type TriadDecisionInquiryV1FvEmeaOK struct {
	Payload *models.TriadDecisionInquiryResponse
}

func (o *TriadDecisionInquiryV1FvEmeaOK) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaOK  %+v", 200, o.Payload)
}

func (o *TriadDecisionInquiryV1FvEmeaOK) GetPayload() *models.TriadDecisionInquiryResponse {
	return o.Payload
}

func (o *TriadDecisionInquiryV1FvEmeaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TriadDecisionInquiryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaBadRequest creates a TriadDecisionInquiryV1FvEmeaBadRequest with default headers values
func NewTriadDecisionInquiryV1FvEmeaBadRequest() *TriadDecisionInquiryV1FvEmeaBadRequest {
	return &TriadDecisionInquiryV1FvEmeaBadRequest{}
}

/*TriadDecisionInquiryV1FvEmeaBadRequest handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-003 - Invalid request. This could be because of invalid data in the request or header, among other reasons.<BR/>API-Sec-004 - Invalid request. The client_assertion JWT is invalid<BR/>API-Sec-013 - The JWT has an invalid expiry. Pleases end a request with a valid JWT
*/
type TriadDecisionInquiryV1FvEmeaBadRequest struct {
	Payload *models.FsErrorDetails
}

func (o *TriadDecisionInquiryV1FvEmeaBadRequest) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaBadRequest  %+v", 400, o.Payload)
}

func (o *TriadDecisionInquiryV1FvEmeaBadRequest) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *TriadDecisionInquiryV1FvEmeaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaUnauthorized creates a TriadDecisionInquiryV1FvEmeaUnauthorized with default headers values
func NewTriadDecisionInquiryV1FvEmeaUnauthorized() *TriadDecisionInquiryV1FvEmeaUnauthorized {
	return &TriadDecisionInquiryV1FvEmeaUnauthorized{}
}

/*TriadDecisionInquiryV1FvEmeaUnauthorized handles this case with default header values.

Unauthorized: Authorization failed due to missing or invalid credentials. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-001 - The auth header has invalid values. Please try with valid values<BR/>API-Sec-002 - The client id provided is invalid. Please try with valid client id<BR/>API-Sec-007 - The access token is invalid. It may have expired, or maybe incorrect
*/
type TriadDecisionInquiryV1FvEmeaUnauthorized struct {
	Payload *models.FsErrorDetails
}

func (o *TriadDecisionInquiryV1FvEmeaUnauthorized) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaUnauthorized  %+v", 401, o.Payload)
}

func (o *TriadDecisionInquiryV1FvEmeaUnauthorized) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *TriadDecisionInquiryV1FvEmeaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaForbidden creates a TriadDecisionInquiryV1FvEmeaForbidden with default headers values
func NewTriadDecisionInquiryV1FvEmeaForbidden() *TriadDecisionInquiryV1FvEmeaForbidden {
	return &TriadDecisionInquiryV1FvEmeaForbidden{}
}

/*TriadDecisionInquiryV1FvEmeaForbidden handles this case with default header values.

Forbidden: Insufficient access for requested operation. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-006 - Replay attack detected. Please try again with valid data<BR/>API-Sec-008 - Mismatch in scope. The access token does not have the permission to access this resource
*/
type TriadDecisionInquiryV1FvEmeaForbidden struct {
	Payload *models.FsErrorDetails
}

func (o *TriadDecisionInquiryV1FvEmeaForbidden) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaForbidden  %+v", 403, o.Payload)
}

func (o *TriadDecisionInquiryV1FvEmeaForbidden) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *TriadDecisionInquiryV1FvEmeaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaNotFound creates a TriadDecisionInquiryV1FvEmeaNotFound with default headers values
func NewTriadDecisionInquiryV1FvEmeaNotFound() *TriadDecisionInquiryV1FvEmeaNotFound {
	return &TriadDecisionInquiryV1FvEmeaNotFound{}
}

/*TriadDecisionInquiryV1FvEmeaNotFound handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-005 - Resource not found
*/
type TriadDecisionInquiryV1FvEmeaNotFound struct {
	Payload *models.FsErrorDetails
}

func (o *TriadDecisionInquiryV1FvEmeaNotFound) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaNotFound  %+v", 404, o.Payload)
}

func (o *TriadDecisionInquiryV1FvEmeaNotFound) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *TriadDecisionInquiryV1FvEmeaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaTooManyRequests creates a TriadDecisionInquiryV1FvEmeaTooManyRequests with default headers values
func NewTriadDecisionInquiryV1FvEmeaTooManyRequests() *TriadDecisionInquiryV1FvEmeaTooManyRequests {
	return &TriadDecisionInquiryV1FvEmeaTooManyRequests{}
}

/*TriadDecisionInquiryV1FvEmeaTooManyRequests handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-009 - You have exceeded the App level quota<BR/>API-Sec-010 - You have exceeded the Developer level quota<BR/>API-Sec-011 - You have exceeded the Product level quota<BR/>API-Sec-012 - Too many requests for this API. Please try after sometime
*/
type TriadDecisionInquiryV1FvEmeaTooManyRequests struct {
	Payload *models.FsErrorDetails
}

func (o *TriadDecisionInquiryV1FvEmeaTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaTooManyRequests  %+v", 429, o.Payload)
}

func (o *TriadDecisionInquiryV1FvEmeaTooManyRequests) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *TriadDecisionInquiryV1FvEmeaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaStatus452 creates a TriadDecisionInquiryV1FvEmeaStatus452 with default headers values
func NewTriadDecisionInquiryV1FvEmeaStatus452() *TriadDecisionInquiryV1FvEmeaStatus452 {
	return &TriadDecisionInquiryV1FvEmeaStatus452{}
}

/*TriadDecisionInquiryV1FvEmeaStatus452 handles this case with default header values.

System Exception: Internal processes not related to client interaction with application are the cause of the failure
*/
type TriadDecisionInquiryV1FvEmeaStatus452 struct {
}

func (o *TriadDecisionInquiryV1FvEmeaStatus452) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaStatus452 ", 452)
}

func (o *TriadDecisionInquiryV1FvEmeaStatus452) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaStatus453 creates a TriadDecisionInquiryV1FvEmeaStatus453 with default headers values
func NewTriadDecisionInquiryV1FvEmeaStatus453() *TriadDecisionInquiryV1FvEmeaStatus453 {
	return &TriadDecisionInquiryV1FvEmeaStatus453{}
}

/*TriadDecisionInquiryV1FvEmeaStatus453 handles this case with default header values.

Validation Exception: The request failed validation, modify the request and resubmit
*/
type TriadDecisionInquiryV1FvEmeaStatus453 struct {
}

func (o *TriadDecisionInquiryV1FvEmeaStatus453) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaStatus453 ", 453)
}

func (o *TriadDecisionInquiryV1FvEmeaStatus453) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTriadDecisionInquiryV1FvEmeaStatus455 creates a TriadDecisionInquiryV1FvEmeaStatus455 with default headers values
func NewTriadDecisionInquiryV1FvEmeaStatus455() *TriadDecisionInquiryV1FvEmeaStatus455 {
	return &TriadDecisionInquiryV1FvEmeaStatus455{}
}

/*TriadDecisionInquiryV1FvEmeaStatus455 handles this case with default header values.

ODS Error Exception: ODS returned a message with transaction status ERROR
*/
type TriadDecisionInquiryV1FvEmeaStatus455 struct {
}

func (o *TriadDecisionInquiryV1FvEmeaStatus455) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/triadDecisionInquiry][%d] triadDecisionInquiryV1FvEmeaStatus455 ", 455)
}

func (o *TriadDecisionInquiryV1FvEmeaStatus455) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
