// Code generated by go-swagger; DO NOT EDIT.

package prepaid

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tooolbox/firstvision/models"
)

// WalletRedemptionV1FvEmeaReader is a Reader for the WalletRedemptionV1FvEmea structure.
type WalletRedemptionV1FvEmeaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WalletRedemptionV1FvEmeaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWalletRedemptionV1FvEmeaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWalletRedemptionV1FvEmeaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewWalletRedemptionV1FvEmeaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewWalletRedemptionV1FvEmeaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewWalletRedemptionV1FvEmeaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewWalletRedemptionV1FvEmeaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 452:
		result := NewWalletRedemptionV1FvEmeaStatus452()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 453:
		result := NewWalletRedemptionV1FvEmeaStatus453()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 455:
		result := NewWalletRedemptionV1FvEmeaStatus455()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWalletRedemptionV1FvEmeaOK creates a WalletRedemptionV1FvEmeaOK with default headers values
func NewWalletRedemptionV1FvEmeaOK() *WalletRedemptionV1FvEmeaOK {
	return &WalletRedemptionV1FvEmeaOK{}
}

/*WalletRedemptionV1FvEmeaOK handles this case with default header values.

successful operation
*/
type WalletRedemptionV1FvEmeaOK struct {
	Payload *models.WalletRedemptionResponse
}

func (o *WalletRedemptionV1FvEmeaOK) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaOK  %+v", 200, o.Payload)
}

func (o *WalletRedemptionV1FvEmeaOK) GetPayload() *models.WalletRedemptionResponse {
	return o.Payload
}

func (o *WalletRedemptionV1FvEmeaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WalletRedemptionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWalletRedemptionV1FvEmeaBadRequest creates a WalletRedemptionV1FvEmeaBadRequest with default headers values
func NewWalletRedemptionV1FvEmeaBadRequest() *WalletRedemptionV1FvEmeaBadRequest {
	return &WalletRedemptionV1FvEmeaBadRequest{}
}

/*WalletRedemptionV1FvEmeaBadRequest handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-003 - Invalid request. This could be because of invalid data in the request or header, among other reasons.<BR/>API-Sec-004 - Invalid request. The client_assertion JWT is invalid<BR/>API-Sec-013 - The JWT has an invalid expiry. Pleases end a request with a valid JWT
*/
type WalletRedemptionV1FvEmeaBadRequest struct {
	Payload *models.FsErrorDetails
}

func (o *WalletRedemptionV1FvEmeaBadRequest) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaBadRequest  %+v", 400, o.Payload)
}

func (o *WalletRedemptionV1FvEmeaBadRequest) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *WalletRedemptionV1FvEmeaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWalletRedemptionV1FvEmeaUnauthorized creates a WalletRedemptionV1FvEmeaUnauthorized with default headers values
func NewWalletRedemptionV1FvEmeaUnauthorized() *WalletRedemptionV1FvEmeaUnauthorized {
	return &WalletRedemptionV1FvEmeaUnauthorized{}
}

/*WalletRedemptionV1FvEmeaUnauthorized handles this case with default header values.

Unauthorized: Authorization failed due to missing or invalid credentials. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-001 - The auth header has invalid values. Please try with valid values<BR/>API-Sec-002 - The client id provided is invalid. Please try with valid client id<BR/>API-Sec-007 - The access token is invalid. It may have expired, or maybe incorrect
*/
type WalletRedemptionV1FvEmeaUnauthorized struct {
	Payload *models.FsErrorDetails
}

func (o *WalletRedemptionV1FvEmeaUnauthorized) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaUnauthorized  %+v", 401, o.Payload)
}

func (o *WalletRedemptionV1FvEmeaUnauthorized) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *WalletRedemptionV1FvEmeaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWalletRedemptionV1FvEmeaForbidden creates a WalletRedemptionV1FvEmeaForbidden with default headers values
func NewWalletRedemptionV1FvEmeaForbidden() *WalletRedemptionV1FvEmeaForbidden {
	return &WalletRedemptionV1FvEmeaForbidden{}
}

/*WalletRedemptionV1FvEmeaForbidden handles this case with default header values.

Forbidden: Insufficient access for requested operation. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-006 - Replay attack detected. Please try again with valid data<BR/>API-Sec-008 - Mismatch in scope. The access token does not have the permission to access this resource
*/
type WalletRedemptionV1FvEmeaForbidden struct {
	Payload *models.FsErrorDetails
}

func (o *WalletRedemptionV1FvEmeaForbidden) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaForbidden  %+v", 403, o.Payload)
}

func (o *WalletRedemptionV1FvEmeaForbidden) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *WalletRedemptionV1FvEmeaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWalletRedemptionV1FvEmeaNotFound creates a WalletRedemptionV1FvEmeaNotFound with default headers values
func NewWalletRedemptionV1FvEmeaNotFound() *WalletRedemptionV1FvEmeaNotFound {
	return &WalletRedemptionV1FvEmeaNotFound{}
}

/*WalletRedemptionV1FvEmeaNotFound handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-005 - Resource not found
*/
type WalletRedemptionV1FvEmeaNotFound struct {
	Payload *models.FsErrorDetails
}

func (o *WalletRedemptionV1FvEmeaNotFound) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaNotFound  %+v", 404, o.Payload)
}

func (o *WalletRedemptionV1FvEmeaNotFound) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *WalletRedemptionV1FvEmeaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWalletRedemptionV1FvEmeaTooManyRequests creates a WalletRedemptionV1FvEmeaTooManyRequests with default headers values
func NewWalletRedemptionV1FvEmeaTooManyRequests() *WalletRedemptionV1FvEmeaTooManyRequests {
	return &WalletRedemptionV1FvEmeaTooManyRequests{}
}

/*WalletRedemptionV1FvEmeaTooManyRequests handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-009 - You have exceeded the App level quota<BR/>API-Sec-010 - You have exceeded the Developer level quota<BR/>API-Sec-011 - You have exceeded the Product level quota<BR/>API-Sec-012 - Too many requests for this API. Please try after sometime
*/
type WalletRedemptionV1FvEmeaTooManyRequests struct {
	Payload *models.FsErrorDetails
}

func (o *WalletRedemptionV1FvEmeaTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaTooManyRequests  %+v", 429, o.Payload)
}

func (o *WalletRedemptionV1FvEmeaTooManyRequests) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *WalletRedemptionV1FvEmeaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWalletRedemptionV1FvEmeaStatus452 creates a WalletRedemptionV1FvEmeaStatus452 with default headers values
func NewWalletRedemptionV1FvEmeaStatus452() *WalletRedemptionV1FvEmeaStatus452 {
	return &WalletRedemptionV1FvEmeaStatus452{}
}

/*WalletRedemptionV1FvEmeaStatus452 handles this case with default header values.

System Exception: Internal processes not related to client interaction with application are the cause of the failure
*/
type WalletRedemptionV1FvEmeaStatus452 struct {
}

func (o *WalletRedemptionV1FvEmeaStatus452) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaStatus452 ", 452)
}

func (o *WalletRedemptionV1FvEmeaStatus452) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWalletRedemptionV1FvEmeaStatus453 creates a WalletRedemptionV1FvEmeaStatus453 with default headers values
func NewWalletRedemptionV1FvEmeaStatus453() *WalletRedemptionV1FvEmeaStatus453 {
	return &WalletRedemptionV1FvEmeaStatus453{}
}

/*WalletRedemptionV1FvEmeaStatus453 handles this case with default header values.

Validation Exception: The request failed validation, modify the request and resubmit
*/
type WalletRedemptionV1FvEmeaStatus453 struct {
}

func (o *WalletRedemptionV1FvEmeaStatus453) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaStatus453 ", 453)
}

func (o *WalletRedemptionV1FvEmeaStatus453) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWalletRedemptionV1FvEmeaStatus455 creates a WalletRedemptionV1FvEmeaStatus455 with default headers values
func NewWalletRedemptionV1FvEmeaStatus455() *WalletRedemptionV1FvEmeaStatus455 {
	return &WalletRedemptionV1FvEmeaStatus455{}
}

/*WalletRedemptionV1FvEmeaStatus455 handles this case with default header values.

ODS Error Exception: ODS returned a message with transaction status ERROR
*/
type WalletRedemptionV1FvEmeaStatus455 struct {
}

func (o *WalletRedemptionV1FvEmeaStatus455) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/walletRedemption][%d] walletRedemptionV1FvEmeaStatus455 ", 455)
}

func (o *WalletRedemptionV1FvEmeaStatus455) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
