// Code generated by go-swagger; DO NOT EDIT.

package account_maintenance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tooolbox/firstvision/models"
)

// DirectDebitUpdateV1FvEmeaReader is a Reader for the DirectDebitUpdateV1FvEmea structure.
type DirectDebitUpdateV1FvEmeaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DirectDebitUpdateV1FvEmeaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDirectDebitUpdateV1FvEmeaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDirectDebitUpdateV1FvEmeaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDirectDebitUpdateV1FvEmeaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDirectDebitUpdateV1FvEmeaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDirectDebitUpdateV1FvEmeaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDirectDebitUpdateV1FvEmeaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 452:
		result := NewDirectDebitUpdateV1FvEmeaStatus452()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 453:
		result := NewDirectDebitUpdateV1FvEmeaStatus453()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 455:
		result := NewDirectDebitUpdateV1FvEmeaStatus455()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDirectDebitUpdateV1FvEmeaOK creates a DirectDebitUpdateV1FvEmeaOK with default headers values
func NewDirectDebitUpdateV1FvEmeaOK() *DirectDebitUpdateV1FvEmeaOK {
	return &DirectDebitUpdateV1FvEmeaOK{}
}

/*DirectDebitUpdateV1FvEmeaOK handles this case with default header values.

successful operation
*/
type DirectDebitUpdateV1FvEmeaOK struct {
	Payload *models.DirectDebitUpdateResponse
}

func (o *DirectDebitUpdateV1FvEmeaOK) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaOK  %+v", 200, o.Payload)
}

func (o *DirectDebitUpdateV1FvEmeaOK) GetPayload() *models.DirectDebitUpdateResponse {
	return o.Payload
}

func (o *DirectDebitUpdateV1FvEmeaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DirectDebitUpdateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectDebitUpdateV1FvEmeaBadRequest creates a DirectDebitUpdateV1FvEmeaBadRequest with default headers values
func NewDirectDebitUpdateV1FvEmeaBadRequest() *DirectDebitUpdateV1FvEmeaBadRequest {
	return &DirectDebitUpdateV1FvEmeaBadRequest{}
}

/*DirectDebitUpdateV1FvEmeaBadRequest handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-003 - Invalid request. This could be because of invalid data in the request or header, among other reasons.<BR/>API-Sec-004 - Invalid request. The client_assertion JWT is invalid<BR/>API-Sec-013 - The JWT has an invalid expiry. Pleases end a request with a valid JWT
*/
type DirectDebitUpdateV1FvEmeaBadRequest struct {
	Payload *models.FsErrorDetails
}

func (o *DirectDebitUpdateV1FvEmeaBadRequest) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaBadRequest  %+v", 400, o.Payload)
}

func (o *DirectDebitUpdateV1FvEmeaBadRequest) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *DirectDebitUpdateV1FvEmeaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectDebitUpdateV1FvEmeaUnauthorized creates a DirectDebitUpdateV1FvEmeaUnauthorized with default headers values
func NewDirectDebitUpdateV1FvEmeaUnauthorized() *DirectDebitUpdateV1FvEmeaUnauthorized {
	return &DirectDebitUpdateV1FvEmeaUnauthorized{}
}

/*DirectDebitUpdateV1FvEmeaUnauthorized handles this case with default header values.

Unauthorized: Authorization failed due to missing or invalid credentials. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-001 - The auth header has invalid values. Please try with valid values<BR/>API-Sec-002 - The client id provided is invalid. Please try with valid client id<BR/>API-Sec-007 - The access token is invalid. It may have expired, or maybe incorrect
*/
type DirectDebitUpdateV1FvEmeaUnauthorized struct {
	Payload *models.FsErrorDetails
}

func (o *DirectDebitUpdateV1FvEmeaUnauthorized) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaUnauthorized  %+v", 401, o.Payload)
}

func (o *DirectDebitUpdateV1FvEmeaUnauthorized) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *DirectDebitUpdateV1FvEmeaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectDebitUpdateV1FvEmeaForbidden creates a DirectDebitUpdateV1FvEmeaForbidden with default headers values
func NewDirectDebitUpdateV1FvEmeaForbidden() *DirectDebitUpdateV1FvEmeaForbidden {
	return &DirectDebitUpdateV1FvEmeaForbidden{}
}

/*DirectDebitUpdateV1FvEmeaForbidden handles this case with default header values.

Forbidden: Insufficient access for requested operation. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-006 - Replay attack detected. Please try again with valid data<BR/>API-Sec-008 - Mismatch in scope. The access token does not have the permission to access this resource
*/
type DirectDebitUpdateV1FvEmeaForbidden struct {
	Payload *models.FsErrorDetails
}

func (o *DirectDebitUpdateV1FvEmeaForbidden) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaForbidden  %+v", 403, o.Payload)
}

func (o *DirectDebitUpdateV1FvEmeaForbidden) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *DirectDebitUpdateV1FvEmeaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectDebitUpdateV1FvEmeaNotFound creates a DirectDebitUpdateV1FvEmeaNotFound with default headers values
func NewDirectDebitUpdateV1FvEmeaNotFound() *DirectDebitUpdateV1FvEmeaNotFound {
	return &DirectDebitUpdateV1FvEmeaNotFound{}
}

/*DirectDebitUpdateV1FvEmeaNotFound handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-005 - Resource not found
*/
type DirectDebitUpdateV1FvEmeaNotFound struct {
	Payload *models.FsErrorDetails
}

func (o *DirectDebitUpdateV1FvEmeaNotFound) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaNotFound  %+v", 404, o.Payload)
}

func (o *DirectDebitUpdateV1FvEmeaNotFound) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *DirectDebitUpdateV1FvEmeaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectDebitUpdateV1FvEmeaTooManyRequests creates a DirectDebitUpdateV1FvEmeaTooManyRequests with default headers values
func NewDirectDebitUpdateV1FvEmeaTooManyRequests() *DirectDebitUpdateV1FvEmeaTooManyRequests {
	return &DirectDebitUpdateV1FvEmeaTooManyRequests{}
}

/*DirectDebitUpdateV1FvEmeaTooManyRequests handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-009 - You have exceeded the App level quota<BR/>API-Sec-010 - You have exceeded the Developer level quota<BR/>API-Sec-011 - You have exceeded the Product level quota<BR/>API-Sec-012 - Too many requests for this API. Please try after sometime
*/
type DirectDebitUpdateV1FvEmeaTooManyRequests struct {
	Payload *models.FsErrorDetails
}

func (o *DirectDebitUpdateV1FvEmeaTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaTooManyRequests  %+v", 429, o.Payload)
}

func (o *DirectDebitUpdateV1FvEmeaTooManyRequests) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *DirectDebitUpdateV1FvEmeaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectDebitUpdateV1FvEmeaStatus452 creates a DirectDebitUpdateV1FvEmeaStatus452 with default headers values
func NewDirectDebitUpdateV1FvEmeaStatus452() *DirectDebitUpdateV1FvEmeaStatus452 {
	return &DirectDebitUpdateV1FvEmeaStatus452{}
}

/*DirectDebitUpdateV1FvEmeaStatus452 handles this case with default header values.

System Exception: Internal processes not related to client interaction with application are the cause of the failure
*/
type DirectDebitUpdateV1FvEmeaStatus452 struct {
}

func (o *DirectDebitUpdateV1FvEmeaStatus452) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaStatus452 ", 452)
}

func (o *DirectDebitUpdateV1FvEmeaStatus452) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDirectDebitUpdateV1FvEmeaStatus453 creates a DirectDebitUpdateV1FvEmeaStatus453 with default headers values
func NewDirectDebitUpdateV1FvEmeaStatus453() *DirectDebitUpdateV1FvEmeaStatus453 {
	return &DirectDebitUpdateV1FvEmeaStatus453{}
}

/*DirectDebitUpdateV1FvEmeaStatus453 handles this case with default header values.

Validation Exception: The request failed validation, modify the request and resubmit
*/
type DirectDebitUpdateV1FvEmeaStatus453 struct {
}

func (o *DirectDebitUpdateV1FvEmeaStatus453) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaStatus453 ", 453)
}

func (o *DirectDebitUpdateV1FvEmeaStatus453) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDirectDebitUpdateV1FvEmeaStatus455 creates a DirectDebitUpdateV1FvEmeaStatus455 with default headers values
func NewDirectDebitUpdateV1FvEmeaStatus455() *DirectDebitUpdateV1FvEmeaStatus455 {
	return &DirectDebitUpdateV1FvEmeaStatus455{}
}

/*DirectDebitUpdateV1FvEmeaStatus455 handles this case with default header values.

ODS Error Exception: ODS returned a message with transaction status ERROR
*/
type DirectDebitUpdateV1FvEmeaStatus455 struct {
}

func (o *DirectDebitUpdateV1FvEmeaStatus455) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/directDebitUpdate][%d] directDebitUpdateV1FvEmeaStatus455 ", 455)
}

func (o *DirectDebitUpdateV1FvEmeaStatus455) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
