// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountAssociationForAccountAdd1 account association for account add1
//
// swagger:model AccountAssociationForAccountAdd1
type AccountAssociationForAccountAdd1 struct {

	//  Max length = 19, Customer number that identifies the Customer Name/Address record of the associated party. Account number must exist and should not be same as account customer number.
	// Max Length: 19
	// Min Length: 0
	AssociationAccountNumber *string `json:"associationAccountNumber,omitempty"`

	//  Max length = 17, Identifies the amount guaranteed by the guarantor. Field must be numeric.
	// Pattern: ^(-)?[0-9]{1,17}$
	AssociationAmount string `json:"associationAmount,omitempty"`

	// Format: YYYYMMDD. Indicates the date on which the guarantor's association ends. Field must be a valid Julian date. Field must be numeric.
	AssociationDate string `json:"associationDate,omitempty"`

	//  Max length = 1, Defines the nature of a guarantor's association with the account. Valid values are 0 - 4. Field must be numeric. 0 = Not used (Default) 1 = Guarantor is married to the account holder and lives at the same address 2 = Guarantor is not married to the account holder and lives at the same address 3= Guarantor is married to the account holder and does not live at the same address 4 = Guarantor is a not married to the account holder and does not live at the same address.
	// Max Length: 1
	// Min Length: 0
	// Pattern: ^[0-9]*$
	AssociationRelType *string `json:"associationRelType,omitempty"`

	//  Max length = 1, code that indicates the type of association with the account. Valid values are 0 - 9. Field  must be numeric 0 = Not used (Default) 1 = Guarantor 2 = Cosigner 3 = Authorized signer 4 = Not used 5-9 = User-defined.
	// Max Length: 1
	// Min Length: 0
	// Pattern: ^[0-9]*$
	AssociationType *string `json:"associationType,omitempty"`
}

// Validate validates this account association for account add1
func (m *AccountAssociationForAccountAdd1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssociationAccountNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssociationAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssociationRelType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssociationType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountAssociationForAccountAdd1) validateAssociationAccountNumber(formats strfmt.Registry) error {

	if swag.IsZero(m.AssociationAccountNumber) { // not required
		return nil
	}

	if err := validate.MinLength("associationAccountNumber", "body", string(*m.AssociationAccountNumber), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("associationAccountNumber", "body", string(*m.AssociationAccountNumber), 19); err != nil {
		return err
	}

	return nil
}

func (m *AccountAssociationForAccountAdd1) validateAssociationAmount(formats strfmt.Registry) error {

	if swag.IsZero(m.AssociationAmount) { // not required
		return nil
	}

	if err := validate.Pattern("associationAmount", "body", string(m.AssociationAmount), `^(-)?[0-9]{1,17}$`); err != nil {
		return err
	}

	return nil
}

func (m *AccountAssociationForAccountAdd1) validateAssociationRelType(formats strfmt.Registry) error {

	if swag.IsZero(m.AssociationRelType) { // not required
		return nil
	}

	if err := validate.MinLength("associationRelType", "body", string(*m.AssociationRelType), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("associationRelType", "body", string(*m.AssociationRelType), 1); err != nil {
		return err
	}

	if err := validate.Pattern("associationRelType", "body", string(*m.AssociationRelType), `^[0-9]*$`); err != nil {
		return err
	}

	return nil
}

func (m *AccountAssociationForAccountAdd1) validateAssociationType(formats strfmt.Registry) error {

	if swag.IsZero(m.AssociationType) { // not required
		return nil
	}

	if err := validate.MinLength("associationType", "body", string(*m.AssociationType), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("associationType", "body", string(*m.AssociationType), 1); err != nil {
		return err
	}

	if err := validate.Pattern("associationType", "body", string(*m.AssociationType), `^[0-9]*$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountAssociationForAccountAdd1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountAssociationForAccountAdd1) UnmarshalBinary(b []byte) error {
	var res AccountAssociationForAccountAdd1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
