// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AtmOtcQsiRtlAccum2ForAccountDetailInquiry2 atm otc qsi rtl accum2 for account detail inquiry2
//
// swagger:model AtmOtcQsiRtlAccum2ForAccountDetailInquiry2
type AtmOtcQsiRtlAccum2ForAccountDetailInquiry2 struct {

	// Group Occurrence. There are 4  occurences. Daily, Cycle to Date, Year to Date and Life To Date. The length of the cocurrences is 26 characters
	DlyCtdYtdLtd []*DlyCtdYtdLtd2ForAccountDetailInquiry2 `json:"dlyCtdYtdLtd"`
}

// Validate validates this atm otc qsi rtl accum2 for account detail inquiry2
func (m *AtmOtcQsiRtlAccum2ForAccountDetailInquiry2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDlyCtdYtdLtd(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtmOtcQsiRtlAccum2ForAccountDetailInquiry2) validateDlyCtdYtdLtd(formats strfmt.Registry) error {

	if swag.IsZero(m.DlyCtdYtdLtd) { // not required
		return nil
	}

	for i := 0; i < len(m.DlyCtdYtdLtd); i++ {
		if swag.IsZero(m.DlyCtdYtdLtd[i]) { // not required
			continue
		}

		if m.DlyCtdYtdLtd[i] != nil {
			if err := m.DlyCtdYtdLtd[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dlyCtdYtdLtd" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AtmOtcQsiRtlAccum2ForAccountDetailInquiry2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AtmOtcQsiRtlAccum2ForAccountDetailInquiry2) UnmarshalBinary(b []byte) error {
	var res AtmOtcQsiRtlAccum2ForAccountDetailInquiry2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
