// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CancelledstoredCard cancelledstored card
//
// swagger:model cancelledstoredCard
type CancelledstoredCard struct {

	// Populate with True or False to indicate if card is the default stored card
	CancelledStoredCardDefault string `json:"cancelledStoredCardDefault,omitempty"`

	// The expiry month of the cancelled stored card.
	CancelledStoredCardExpiryMonth string `json:"cancelledStoredCardExpiryMonth,omitempty"`

	// The expiry year of the cancelled stored.
	CancelledStoredCardExpiryYear string `json:"cancelledStoredCardExpiryYear,omitempty"`

	// The last 4 digits of the cancelled stored card's number.
	CancelledStoredCardNumberLast4Digits string `json:"cancelledStoredCardNumberLast4Digits,omitempty"`

	// A reason Code relating to reason for stored card cancellation. Populate with 1, 2, 3 or 4.  <BR/> 1-Customer, <BR/> 2-Expired, <BR/> 3-Dormant, <BR/> 4-Issuer Rule.
	CancelledStoredCardReasonCode string `json:"cancelledStoredCardReasonCode,omitempty"`

	// Description relating to reason for stored card cancellation. Populate with Customer, Expired, Dormant or Issuer Rule.
	CancelledStoredCardReasonDescription string `json:"cancelledStoredCardReasonDescription,omitempty"`

	// The cancelled stored card scheme e.g. Visa, MasterCard
	CancelledStoredCardScheme string `json:"cancelledStoredCardScheme,omitempty"`

	// The name of the cancelled stored card
	CancelledstoredCardName string `json:"cancelledstoredCardName,omitempty"`
}

// Validate validates this cancelledstored card
func (m *CancelledstoredCard) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CancelledstoredCard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CancelledstoredCard) UnmarshalBinary(b []byte) error {
	var res CancelledstoredCard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
