// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FiScrsForAccountOverview1 fi scrs for account overview1
//
// swagger:model FiScrsForAccountOverview1
type FiScrsForAccountOverview1 struct {

	//  Max length = 4, Behaviour Scores returned from TRIAD.
	FiScr string `json:"fiScr,omitempty"`
}

// Validate validates this fi scrs for account overview1
func (m *FiScrsForAccountOverview1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FiScrsForAccountOverview1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FiScrsForAccountOverview1) UnmarshalBinary(b []byte) error {
	var res FiScrsForAccountOverview1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
