// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FiScoresForAccountDetailInquiry1 fi scores for account detail inquiry1
//
// swagger:model FiScoresForAccountDetailInquiry1
type FiScoresForAccountDetailInquiry1 struct {

	//  Max length = 4, Triad Score. This is a signed value
	FiScore string `json:"fiScore,omitempty"`
}

// Validate validates this fi scores for account detail inquiry1
func (m *FiScoresForAccountDetailInquiry1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FiScoresForAccountDetailInquiry1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FiScoresForAccountDetailInquiry1) UnmarshalBinary(b []byte) error {
	var res FiScoresForAccountDetailInquiry1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
