// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LoyaltySummaryRequest loyalty summary request
//
// swagger:model LoyaltySummaryRequest
type LoyaltySummaryRequest struct {

	//  Max length = 19, ACCOUNT NBR
	// Max Length: 19
	// Min Length: 0
	AccountNbr *string `json:"accountNbr,omitempty"`

	// common
	Common *Header `json:"common,omitempty"`
}

// Validate validates this loyalty summary request
func (m *LoyaltySummaryRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountNbr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCommon(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LoyaltySummaryRequest) validateAccountNbr(formats strfmt.Registry) error {

	if swag.IsZero(m.AccountNbr) { // not required
		return nil
	}

	if err := validate.MinLength("accountNbr", "body", string(*m.AccountNbr), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("accountNbr", "body", string(*m.AccountNbr), 19); err != nil {
		return err
	}

	return nil
}

func (m *LoyaltySummaryRequest) validateCommon(formats strfmt.Registry) error {

	if swag.IsZero(m.Common) { // not required
		return nil
	}

	if m.Common != nil {
		if err := m.Common.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("common")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LoyaltySummaryRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoyaltySummaryRequest) UnmarshalBinary(b []byte) error {
	var res LoyaltySummaryRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
