// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NameAddressTblForAddressHistoryInquiry1 name address tbl for address history inquiry1
//
// swagger:model NameAddressTblForAddressHistoryInquiry1
type NameAddressTblForAddressHistoryInquiry1 struct {

	//  Max length = 40, Address Line 1 of the customer as defined on the Customer Name/Address record.
	NaAddr1 string `json:"naAddr1,omitempty"`

	//  Max length = 40, Address Line 2 of the customer as defined on the Customer Name/Address record.
	NaAddr2 string `json:"naAddr2,omitempty"`

	//  Max length = 40, Mailing address line 3 for the customer Group variable of below 2 fields  All the below two fields need to be passed to update ADDR-3.
	NaAddr3 string `json:"naAddr3,omitempty"`

	//  Max length = 40, Mailing address line 4 for the customer
	NaAddr4 string `json:"naAddr4,omitempty"`

	//  Max length = 30, City: City portion of the mailing address.
	NaCity string `json:"naCity,omitempty"`

	//  Max length = 3, ISO Country code of the mailing address.
	NaCntryCd string `json:"naCntryCd,omitempty"`

	// Format: YYYYMMDD. Date of birth of the Customer. Must be a valid date. Date format is CCYYMMDD
	NaDob string `json:"naDob,omitempty"`

	//  Max length = 60, Email: E-mail address of the cardholder.
	NaEmail string `json:"naEmail,omitempty"`

	//  Max length = 1, Code that specifies whether the customer giv e permission to send emails to this address. The values are: 0 = No, do not contact the customer at this number 1 = Yes, you can contact the customer at this number (Default) 2 = Preferred contact methodWork
	NaEmailFlag string `json:"naEmailFlag,omitempty"`

	//  Max length = 40, Employer: Name of the employer of the cardholder.
	NaEmployer string `json:"naEmployer,omitempty"`

	//  Max length = 40, Mailing address of the employer of the customer
	NaEmployerAddr1 string `json:"naEmployerAddr1,omitempty"`

	//  Max length = 40, Mailing address of the employer of the customer (cont.)
	NaEmployerAddr2 string `json:"naEmployerAddr2,omitempty"`

	//  Max length = 20, Fax number of the accountholder.
	NaFaxPhone string `json:"naFaxPhone,omitempty"`

	//  Max length = 1, Fax Flag: Code that specifies whether the customer grants permission to use this number. Values are: 0 = No, do not contact the customer at this number 1 = Yes, you can contact the customer at this number (Default) 2 = Preferred contact method
	NaFaxPhoneFlag string `json:"naFaxPhoneFlag,omitempty"`

	//  Max length = 20, Home phone number of the accountholder.
	NaHomePhone string `json:"naHomePhone,omitempty"`

	//  Max length = 1, Home Phone Flag: Code that specifies whether the customer grants permission to  call this number. Values are: 0 = No, do not contact the customer at this number 1 = Yes, you can contact the customer at this number (Default) 2 = Preferred contact method.
	NaHomePhoneFlag string `json:"naHomePhoneFlag,omitempty"`

	//  Max length = 40, House name of the customer.
	NaHouseName string `json:"naHouseName,omitempty"`

	//  Max length = 20, House number of the customer.
	NaHouseNumber string `json:"naHouseNumber,omitempty"`

	//  Max length = 3, Language Indicator.
	NaLanguageInd string `json:"naLanguageInd,omitempty"`

	//  Max length = 1, Mailing List: User-defined code that indicates whether the customer wants to be on a mailing list. Values are: Y = Yes, the owner wants to be on a mailing list (Default) N = No, the owner does not want to be on a mailing list.
	NaMailingList string `json:"naMailingList,omitempty"`

	//  Max length = 20, Mobile number of the accountholder.
	NaMobilePhone string `json:"naMobilePhone,omitempty"`

	//  Max length = 1, Mobile Phone Flag: Code that specifies whether the customer grants permission to  call this number.  Values are: 0 = No, do not contact the customer at this number 1 = Yes, you can contact the customer at this number (Default) 2 = Preferred contact method
	NaMobilePhoneFlag string `json:"naMobilePhoneFlag,omitempty"`

	//  Max length = 40, Name line 1 of the customer as defined on the Customer Name/Address record.
	NaNameLine1 string `json:"naNameLine1,omitempty"`

	//  Max length = 40, Name line 2 of the customer as defined on the Customer Name/Address record.
	NaNameLine2 string `json:"naNameLine2,omitempty"`

	//  Max length = 40, Name line 3 of the customer as defined on the Customer Name/Address record.
	NaNameLine3 string `json:"naNameLine3,omitempty"`

	//  Max length = 1, Name Type Indicator 1: Indicates the type of name. Values are: 0 = Personal name (Default) 1 = Business name 2 = Store name 3 = Generic name.
	NaNameTypeInd1 string `json:"naNameTypeInd1,omitempty"`

	//  Max length = 1, Indicates the type of name. Valid values are: 0 = Personal name (Default) 1 = Business name 2 = Store name 3 = Generic name.
	NaNameTypeInd2 string `json:"naNameTypeInd2,omitempty"`

	//  Max length = 1, Indicates the type of name. Valid values are: 0 = Personal name (Default) 1 = Business name 2 = Store name 3 = Generic name.
	NaNameTypeInd3 string `json:"naNameTypeInd3,omitempty"`

	//  Max length = 10, Postal Code: Postal code portion of the mailing address.
	NaPstlCd string `json:"naPstlCd,omitempty"`

	//  Max length = 1, SMS Flag: code that indicates whether you have permission from the owner to SMS.  Values are:  0 - Do not send  1 - May be sent
	NaSmsFlag string `json:"naSmsFlag,omitempty"`

	//  Max length = 3, State: State or province portion of the mailing address.
	NaState string `json:"naState,omitempty"`

	//  Max length = 1, Statement Message Indicator: indicator that identifies the version of the statement messages used for this customer. The VERSION number defines each the specific statement message table used for this customer.
	NaStmtMsgInd string `json:"naStmtMsgInd,omitempty"`

	//  Max length = 2, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser1 string `json:"naUser1,omitempty"`

	//  Max length = 8, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.  Must be numeric and in valid date format
	NaUser10 string `json:"naUser10,omitempty"`

	//  Max length = 8, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.  Must be numeric and in valid date format
	NaUser11 string `json:"naUser11,omitempty"`

	//  Max length = 30, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser12 string `json:"naUser12,omitempty"`

	//  Max length = 30, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser13 string `json:"naUser13,omitempty"`

	//  Max length = 2, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser2 string `json:"naUser2,omitempty"`

	//  Max length = 7, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser3 string `json:"naUser3,omitempty"`

	//  Max length = 1, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser4 string `json:"naUser4,omitempty"`

	//  Max length = 1, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser5 string `json:"naUser5,omitempty"`

	//  Max length = 2, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser6 string `json:"naUser6,omitempty"`

	//  Max length = 2, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser7 string `json:"naUser7,omitempty"`

	//  Max length = 3, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser8 string `json:"naUser8,omitempty"`

	//  Max length = 3, User defined field. This field can be defined by each business to store information that is not provided in other fields in the system but still is necessary because of the business processes.
	NaUser9 string `json:"naUser9,omitempty"`

	//  Max length = 20, User-defined customer demographic field-1
	NaUserDemo1 string `json:"naUserDemo1,omitempty"`

	//  Max length = 20, User-defined customer demographic field-2
	NaUserDemo2 string `json:"naUserDemo2,omitempty"`

	//  Max length = 20, User-defined customer demographic field-3
	NaUserDemo3 string `json:"naUserDemo3,omitempty"`

	//  Max length = 6, Extension number of the Work phone.
	NaWorkPhExtn string `json:"naWorkPhExtn,omitempty"`

	//  Max length = 20, Employee Phone: Work telephone number of the customer.
	NaWorkPhone string `json:"naWorkPhone,omitempty"`

	//  Max length = 1, WorkPhone Flag: Code that specifies whether the customer grants permission to  call this number. Values are: 0 = No, do not contact the customer at this number 1 = Yes, you can contact the customer at this number (Default) 2 = Preferred contact method.
	NaWorkPhoneFlag string `json:"naWorkPhoneFlag,omitempty"`
}

// Validate validates this name address tbl for address history inquiry1
func (m *NameAddressTblForAddressHistoryInquiry1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NameAddressTblForAddressHistoryInquiry1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NameAddressTblForAddressHistoryInquiry1) UnmarshalBinary(b []byte) error {
	var res NameAddressTblForAddressHistoryInquiry1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
