// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PaymentDueEstimationRequest payment due estimation request
//
// swagger:model PaymentDueEstimationRequest
type PaymentDueEstimationRequest struct {

	//  Max length = 19, Account Number: Number of Customer's account. Must be numeric and greater than zero.
	// Max Length: 19
	// Min Length: 0
	AcctNbr *string `json:"acctNbr,omitempty"`

	//  Max length = 17, Payment amount to be added the account balance to calculate the estimated payment due amounts.
	// Pattern: ^(-)?[0-9]{1,17}$
	AddPymt string `json:"addPymt,omitempty"`

	//  Max length = 17, Spend amount to be added the account balance to calculate the estimated payment due amounts.
	// Pattern: ^(-)?[0-9]{1,17}$
	AddSpend string `json:"addSpend,omitempty"`

	// common
	Common *Header `json:"common,omitempty"`
}

// Validate validates this payment due estimation request
func (m *PaymentDueEstimationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAcctNbr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAddPymt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAddSpend(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCommon(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PaymentDueEstimationRequest) validateAcctNbr(formats strfmt.Registry) error {

	if swag.IsZero(m.AcctNbr) { // not required
		return nil
	}

	if err := validate.MinLength("acctNbr", "body", string(*m.AcctNbr), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("acctNbr", "body", string(*m.AcctNbr), 19); err != nil {
		return err
	}

	return nil
}

func (m *PaymentDueEstimationRequest) validateAddPymt(formats strfmt.Registry) error {

	if swag.IsZero(m.AddPymt) { // not required
		return nil
	}

	if err := validate.Pattern("addPymt", "body", string(m.AddPymt), `^(-)?[0-9]{1,17}$`); err != nil {
		return err
	}

	return nil
}

func (m *PaymentDueEstimationRequest) validateAddSpend(formats strfmt.Registry) error {

	if swag.IsZero(m.AddSpend) { // not required
		return nil
	}

	if err := validate.Pattern("addSpend", "body", string(m.AddSpend), `^(-)?[0-9]{1,17}$`); err != nil {
		return err
	}

	return nil
}

func (m *PaymentDueEstimationRequest) validateCommon(formats strfmt.Registry) error {

	if swag.IsZero(m.Common) { // not required
		return nil
	}

	if m.Common != nil {
		if err := m.Common.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("common")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PaymentDueEstimationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentDueEstimationRequest) UnmarshalBinary(b []byte) error {
	var res PaymentDueEstimationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
