// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlanTable2ForAnnualStatementInquiry2 plan table2 for annual statement inquiry2
//
// swagger:model PlanTable2ForAnnualStatementInquiry2
type PlanTable2ForAnnualStatementInquiry2 struct {

	// Plan Data; 2  Occurrences: (1) = Total of Initial Transactions (2) = Total of Reversal Transactions
	PlanData []*PlanData2ForAnnualStatementInquiry2 `json:"planData"`
}

// Validate validates this plan table2 for annual statement inquiry2
func (m *PlanTable2ForAnnualStatementInquiry2) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlanData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanTable2ForAnnualStatementInquiry2) validatePlanData(formats strfmt.Registry) error {

	if swag.IsZero(m.PlanData) { // not required
		return nil
	}

	for i := 0; i < len(m.PlanData); i++ {
		if swag.IsZero(m.PlanData[i]) { // not required
			continue
		}

		if m.PlanData[i] != nil {
			if err := m.PlanData[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("planData" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlanTable2ForAnnualStatementInquiry2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanTable2ForAnnualStatementInquiry2) UnmarshalBinary(b []byte) error {
	var res PlanTable2ForAnnualStatementInquiry2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
