// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserFieldsForOfferEnrolmentInquiry1 user fields for offer enrolment inquiry1
//
// swagger:model UserFieldsForOfferEnrolmentInquiry1
type UserFieldsForOfferEnrolmentInquiry1 struct {

	//  Max length = 10, User field 4.
	UserField string `json:"userField,omitempty"`
}

// Validate validates this user fields for offer enrolment inquiry1
func (m *UserFieldsForOfferEnrolmentInquiry1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserFieldsForOfferEnrolmentInquiry1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserFieldsForOfferEnrolmentInquiry1) UnmarshalBinary(b []byte) error {
	var res UserFieldsForOfferEnrolmentInquiry1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
